//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LogReclamo
    {
        public string nombreCliente { get; set; }
        public string nombreFuncionario { get; set; }
        public int numReclamo { get; set; }
        public string tipoReclamo { get; set; }
        public string latitud { get; set; }
        public string longitud { get; set; }
        public Nullable<System.DateTime> fechaHora { get; set; }
        public string estado { get; set; }
        public string observacionesCiudadno { get; set; }
        public string observacionesCuadrilla { get; set; }
        public string comentarioFuncionario { get; set; }
    }
}
